[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
directories = { version = "6.0.0" }
reqwest = { version = "0.12.15", features = ["json", "cookies", "multipart"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tokio = { version = "1.44.1", features = ["full"] }

[package]
edition = "2024"
name = "clonk"
version = "0.0.1"
